- nilsbore/geographic_info
- nilsbore/rosbridge_suite
- smarc-project/smarc_msgs
- smarc-project/imc_ros_bridge
- smarc-project/lolo_common
- smarc-project/smarc_navigation
- smarc-project/smarc_missions
- smarc-project/sam_common
- smarc-project/smarc_utils
- nilsbore/roswasm_suite
- smarc-project/sam_webgui
- smarc-project/lolo_webgui
- nilsbore/cola2_msgs_mirror
- smarc-project/stonefish_ros
- smarc-project/smarc_stonefish_sims
- smarc-project-native-gui/roswasm_suite_native
- smarc-project-native-gui/sam_webgui_native
- smarc-project-native-gui/lolo_webgui_native
- smarc-project/smarc_controllers
- smarc-project/uavcan_ros_bridge
- smarc-project/smarc_base
- smarc-project/smarc_desktop
