- nilsbore/geographic_info
- nilsbore/rosbridge_suite
- smarc-project/smarc_msgs
- smarc-project/imc_ros_bridge
- smarc-project/lolo_common
- smarc-project/smarc_navigation
- smarc-project/smarc_missions
- smarc-project/sam_common
- smarc-project/smarc_utils
- nilsbore/roswasm_suite
- nilsbore/sam_webgui
- nilsbore/cola2_msgs_mirror
- nilsbore/stonefish_ros
